name: hn_app
description: Project from The Boring Flutter Development Show

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  url_launcher: ^6.1.4
  built_collection: ^5.0.0
  built_value: ^8.0.0
  http: ^0.13.4
  rxdart: ^0.27.4
  font_awesome_flutter: ^10.1.0
  webview_flutter: ^3.0.4
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner: ^1.0.0
  built_value_generator: ^8.3.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Garamond
      fonts:
        - asset: fonts/CormorantGaramond-Regular.ttf