name: hn_app
description: Project from The Boring Flutter Development Show

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  url_launcher: ^6.1.4
  built_collection: ^5.0.0
  built_value: ^8.0.0
  http: ^0.13.4
  rxdart: ^0.27.4
  font_awesome_flutter: ^10.1.0
  webview_flutter: ^3.0.4
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  drift: ^2.0.2
  path_provider: ^2.0.11
  sqlite3_flutter_libs: ^0.5.0
  logging: ^1.0.2
  google_fonts: ^3.0.1
  path: ^1.8.2
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner: ^2.2.0
  built_value_generator: ^8.4.1
  drift_dev: ^2.0.2
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Garamond
      fonts:
        - asset: fonts/CormorantGaramond-Regular.ttf